"""Add Accounts table

Revision ID: 7de4b5e555e4
Revises: 
Create Date: 2025-06-20 23:10:25.937887

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7de4b5e555e4'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('_password', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('broker', sa.String(), nullable=True),
    sa.Column('server_type', sa.String(), nullable=True),
    sa.Column('api_url', sa.String(), nullable=True),
    sa.Column('api_port', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    # ### end Alembic commands ###
