"""Update fields for Accounts table

Revision ID: 9da4d243ab48
Revises: 7de4b5e555e4
Create Date: 2025-06-20 23:38:46.168139

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9da4d243ab48'
down_revision = '7de4b5e555e4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_from', sa.String(), nullable=True))
    op.drop_column('accounts', 'api_key')
    op.drop_column('accounts', 'api_port')
    op.drop_column('accounts', 'broker')
    op.drop_column('accounts', 'api_url')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('api_url', sa.VARCHAR(), nullable=True))
    op.add_column('accounts', sa.Column('broker', sa.VARCHAR(), nullable=True))
    op.add_column('accounts', sa.Column('api_port', sa.INTEGER(), nullable=True))
    op.add_column('accounts', sa.Column('api_key', sa.VARCHAR(), nullable=True))
    op.drop_column('accounts', 'account_from')
    # ### end Alembic commands ###
